version: 0.1.{build}.beta

branches:
  only:
    - master

  except:
    - gh-pages
    
init:
  - cinst autoit.commandline

build: off

test_script:
  - git submodule update --init --recursive
  - cd test
  - autoit3 /ErrorStdOut /AutoIt3ExecuteScript imperius.test.au3 ci
